import type { Metadata } from "next";
import "./globals.css";
import Sidenav from "./ui/sidebar/sidenav";
import SessionWrapper from "./SessionWrapper";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <SessionWrapper>
      <html lang="en">
        {/* <body className="flex justify-center h-screen p-3 gap-5"> */}
        <body className="bg-[#F5F5F5]">
          {/* <Sidenav /> */}
          {children}
        </body>
      </html>
    </SessionWrapper>
  );
}
